// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thesis.Infrastructure.Data;

#nullable disable

namespace Thesis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508004934_RemoveDyn")]
    partial class RemoveDyn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thesis.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CollectedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("collected_amount");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd86daa5-3736-4bc3-8558-6e4e6cb142b5"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Сбор средств на покупку школьных принадлежностей, одежды и рюкзаков для 50 детей из региональных детдомов. В комплект входит: рюкзак, канцелярия, форма, спортивная одежда.",
                            Status = "Active",
                            TargetAmount = 150000m,
                            Title = "Школьные рюкзаки для детей из детдомов"
                        },
                        new
                        {
                            Id = new Guid("0300b30c-644a-41bb-99b8-e55fbecce271"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Сбор на курс терапии для 5-летнего Артёма, которому требуется дорогостоящее лечение за рубежом. Средства направляются в фонд «Надежда» с полным отчётом о расходах.",
                            Status = "Active",
                            TargetAmount = 2500000m,
                            Title = "Лечение ребёнка с редким заболеванием"
                        },
                        new
                        {
                            Id = new Guid("149dbd7d-3545-430d-a216-90497b8955a6"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Благотворительный проект по созданию уютной игровой зоны для детей, проходящих длительное лечение. Включает: мягкую мебель, развивающие игрушки, книги, мультимедийное оборудование.",
                            Status = "Completed",
                            TargetAmount = 300000m,
                            Title = "Ремонт игровой комнаты в онкоцентре"
                        },
                        new
                        {
                            Id = new Guid("1f49c201-5c87-470f-b2bf-5dc23b0ff45d"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Подготовка и вручение новогодних подарков 200 детям из малообеспеченных семей и социальных центров. Каждый подарок включает: сладости, игрушки, тёплые вещи, письмо от Деда Мороза.",
                            Status = "Pending",
                            TargetAmount = 400000m,
                            Title = "Новогодние подарки для подопечных фондов"
                        },
                        new
                        {
                            Id = new Guid("7feb015d-b162-4f93-b944-3a8a4ccbd61c"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Проект создан для тестирования функционала отмены и архивации. Не является реальным сбором.",
                            Status = "Canceled",
                            TargetAmount = 10000m,
                            Title = "Старый тестовый проект"
                        });
                });

            modelBuilder.Entity("Thesis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66d484b7-ccd6-4dbe-9c3a-3649fb9b64cb"),
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Email = "user@example.com",
                            Name = "Regular User",
                            PasswordHash = "$2a$12$khWKbTxqEJcCiJj4Wfz9ReE27eQQsjQzylH4GYEfq/uz3hRUdvgRi",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c0df61de-cc12-483b-98a5-0279eaa34d19"),
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$12$y7rbIj26aVAoJWXwMzmMjO/UPrdn7FnMNCeTLk7.fEYo2Vg2/WlqS",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
