// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thesis.Infrastructure.Data;

#nullable disable

namespace Thesis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thesis.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CollectedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("collected_amount");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_urls");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd86daa5-3736-4bc3-8558-6e4e6cb142b5"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Сбор средств на покупку школьных принадлежностей...",
                            PhotoUrls = "https://picsum.photos/200?random=117;https://picsum.photos/200?random=13;https://picsum.photos/200?random=17",
                            Status = "Active",
                            TargetAmount = 150000m,
                            Title = "Школьные рюкзаки для детей из детдомов",
                            WalletAddress = "0x1234567890abcdef1234567890abcdef12345678"
                        },
                        new
                        {
                            Id = new Guid("0300b30c-644a-41bb-99b8-e55fbecce271"),
                            CollectedAmount = 0m,
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Description = "Сбор на курс терапии...",
                            PhotoUrls = "https://picsum.photos/200?random=16;https://picsum.photos/200?random=11;https://picsum.photos/200?random=34",
                            Status = "Active",
                            TargetAmount = 2500000m,
                            Title = "Лечение ребёнка с редким заболеванием",
                            WalletAddress = "0x2345678901abcdef2345678901abcdef23456789"
                        });
                });

            modelBuilder.Entity("Thesis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66d484b7-ccd6-4dbe-9c3a-3649fb9b64cb"),
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Email = "user@example.com",
                            Name = "Regular User",
                            PasswordHash = "$2a$12$khWKbTxqEJcCiJj4Wfz9ReE27eQQsjQzylH4GYEfq/uz3hRUdvgRi",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c0df61de-cc12-483b-98a5-0279eaa34d19"),
                            CreatedAt = new DateOnly(2026, 5, 10),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$12$y7rbIj26aVAoJWXwMzmMjO/UPrdn7FnMNCeTLk7.fEYo2Vg2/WlqS",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Thesis.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Thesis.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Thesis.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Thesis.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
